name: "wordcloud"

on:
  issues:
    types: [opened]

jobs:
  addWord:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'wordcloud|')
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        gem install octokit -N --silent
        pip install wordcloud

    - name: Generate New Word Cloud
      run: |
        ruby <<- EORUBY
          require './wordcloud/runner'
          
          Runner.new(
            github_token: '${{ secrets.GITHUB_TOKEN }}',
            issue_number: ENV.fetch('EVENT_ISSUE_NUMBER'),
            issue_title: '${{ github.event.issue.title }}',
            repository: ENV.fetch('REPOSITORY'),
            user: ENV.fetch('EVENT_USER_LOGIN'),
          ).run

        EORUBY
        
    - name: Update Image and Word List
      run: |
        git add README.md wordcloud.png wordcloud/wordlist.txt
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Update Wordcloud" -a || echo "No changes to commit"
        git push
